### ISSUE TITLE
webpack 教程中一个小错误

### ISSUE THREAD

**Issue by ywzhaiqi** [chenxsan/blog#10]
https://www.zfanw.com/blog/webpack-tutorial.html

```js
import $ from 'jquery'
```
>webpack 原生也仅支持 CommonJS 的那种写法

目前 webpack 支持 import 这种写法，无需 `babel-loader`

**Comment by chenxsan** [comment]
@ywzhaiqi Thanks.

**Comment by chenxsan** [comment]
感谢，内容已更新 https://blog.zfanw.com/webpack-tutorial
