### ISSUE TITLE
一个 react-native 下使用 redux 的错误

### ISSUE THREAD

**Issue by guoliang1206** [chenxsan/blog#11]
https://www.zfanw.com/blog/react-native-redux-expected-a-component-class-got-object-object.html

The reason of this error not is that component name as same as register name, the reason is a class in react-native, first letter must be uppercase

**Comment by chenxsan** [comment]
Thanks for you input, I've never thought it could be this problem.

**Comment by chenxsan** [comment]
Will update it when my new blog site get deployed.
