### ISSUE TITLE
使用 Privoxy 屏蔽网页广告

### ISSUE THREAD

**Issue by gyict** [chenxsan/blog#4]
https://www.zfanw.com/blog/block-webpage-ad-with-privoxy.html

您好，我有个问题，我定义规则之后不起作用是怎么回事呢？
页面上显示enable但是访问的网页是直接访问的，没有被forward,这个对filter有影响吗？

**Comment by chenxsan** [comment]
http://config.privoxy.org/show-url-info 网址输入进去，看看匹配的规则有哪些。

**Comment by gyict** [comment]
我直接输入的网址，是可以匹配的，我发现好像是只能对http起作用，而我的网址都走的https，您知道这个该怎么解决吗

**Comment by chenxsan** [comment]
Privoxy 对 https 能做的限于域名部分，https://www.privoxy.org/faq/misc.html#SSL

**Comment by gyict** [comment]
非常感谢您的帮助:)
