### ISSUE TITLE
webpack 教程

### ISSUE THREAD

**Issue by woaixiaojuan** [chenxsan/blog#8]
https://www.zfanw.com/blog/webpack-tutorial.html

index.js 就是main.js，安装babel后执行报错如下：
ERROR in multi (webpack)-dev-server/client?http://localhost:8080 ./index.js
Module not found: Error: Can't resolve 'babel' in 'C:\Users\yangy\Desktop\webpackstudy'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'babel-loader' instead of 'babel',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./index.js

**Comment by chenxsan** [comment]
可能是 webpack 版本更新导致配置失败吧，等我找时间更新下内容。

**Comment by chenxsan** [comment]
已更新 https://blog.zfanw.com/webpack-tutorial，感谢提醒。
